### PR TITLE
Suggestion for concurrent find/replace (serving feature request #1)

### PR DESCRIPTION
**Pull request by RaiKoHoff**
see issue #1

### CODE REVIEW

**Comment by stefankueng** [comment]
thanks for the pull request.
But I'm not really comfortable with your solution: you first do the file enumeration and only then start doing the search. While this makes it possible to do a proper progress info, it will be slower than necessary because the files are accessed twice not right after each other but after all other files have been accessed, and that makes it slower because the filesystem has a cache too which won't help such a situation.

What I'd like to do is using a thread pool, and add items to that pool while enumerating the files. The thread pool class should wait on the "add" method if all threads in the pool are busy until one threads becomes free.

**Comment by RaiKoHoff** [comment]
@stefankueng : exactly the "threadpool" thing is what the std:async/std::future stuff is about (just using the C++11 high-level threadpool abstraction layer. And as a side-effect, you get the file counting ;-)

**Comment by stefankueng** [comment]
I know that. The problem with your approach is that all the futures are created first and then worked on. What I'm imagining is a way to only create the futures that can be currently worked on, and only add more along the way.

imagine a folder with 500'000 files to be searched - memory usage would increase a lot.

**Comment by RaiKoHoff** [comment]
@stefankueng : okay a folder with 500'000 files would be a problem - you have to split in chunks.
As the title says, just a suggestion ...

**Comment by stefankueng** [comment]
And don't forget all those people who search whole drives.
Just search the issue tracker: you'll find people who search a lot more files than (just) 500'000

**Comment by stefankueng** [comment]
It's a shame to close such a pull request into which you put so much work.
Sorry!

**Comment by stefankueng** [comment]
@RaiKoHoff if you like you can review my attempt. I just pushed my changes.

**Pull request closed without merging**
